### PR TITLE
doc: restrucutre of data specs

### PR DESCRIPTION
**Pull request by vesnikos**
- **initial commit**
- **moved readme file back in  root folder**
- **docs: Update Airbnb data product links and minor clarifications**

### CODE REVIEW

**Comment by vesnikos** [comment]
I plan to merge this by the EOB today for the meeting monday; let me know here if there are any objections or if you think you need more time to postpone. cc @Basolanilla @laoserra @ErmiaUOG

**Comment by laoserra** [comment]
"These tables bellow contain the bulk of the information that are used in the processes." 
Which processes? I would rather say here that these two tables are the only ones we need for the airbnb data platform. 

The links in [Research Data Products](https://github.com/vesnikos/ubdc-dags/tree/doc/restructure-of-data-specs/dags/airbnb#research-data-products) have all the same content. Is this supposed to be like that?

Also in the [primary sources](https://github.com/vesnikos/ubdc-dags/blob/doc/restructure-of-data-specs/dags/airbnb/data_specs/primary-sources.md), I personally would like to have a diagram with the schema of the database. See example below for the cctv db.
schema_postgres

These links (from workflow link) return nothing:
pipelines: [1-daily-backups/dags.py](https://github.com/vesnikos/ubdc-dags/blob/doc/restructure-of-data-specs/dags/airbnb/airbnb_daily_responses/1-daily-backups/dags.py)
tests: [tests.py](https://github.com/vesnikos/ubdc-dags/blob/doc/restructure-of-data-specs/dags/tests/airbnb/1-daily-backups/tests.py)

In the [Workflow Datasets](https://github.com/vesnikos/ubdc-dags/tree/doc/restructure-of-data-specs/dags/airbnb#workflow-datasets) I think it will be better if you link the intermediate datasets with final datasets that will be made available to researchers.

**Comment by laoserra** [comment]
Apart from my previous comments, I think you did a great job @vesnikos!

**Review by ErmiaUOG — APPROVED** [review]
LGTM!

**Comment by laoserra** [comment]
made some comments on pull request.

**Comment by vesnikos** [comment]
Good comments, read bellow


> "These tables bellow contain the bulk of the information that are used in the processes." Which processes? I would rather say here that these two tables are the only ones we need for the airbnb data platform.

i rewrote the phrase taking out the work processes and made it more clear that these tables are available to airflow to connect

> 
> The links in [Research Data Products](https://github.com/vesnikos/ubdc-dags/tree/doc/restructure-of-data-specs/dags/airbnb#research-data-products) have all the same content. Is this supposed to be like that?

no its wrong. fixed it

> 
> Also in the [primary sources](https://github.com/vesnikos/ubdc-dags/blob/doc/restructure-of-data-specs/dags/airbnb/data_specs/primary-sources.md), I personally would like to have a diagram with the schema of the database. See example below for the cctv db. schema_postgres
> 

Github's markdown support the mermaid diagraming languange. I think it's a good way to embed interactive graphs here. [example](https://mermaid.live/edit#pako:eNpVjk9Pg0AQxb_KZk6aQFP-iLIHE0u1FxKN9iRwmMDCkpZdsiypCHx3F5oYndPMvPd7MyPksmBAoTzLS85RaRK_p4KYekoirupON9hlxLYfpwPTpJGCDRPZ3Rwk6bhs21pUt1f_bjGRaIwXGyOa1-I0X6Vo5V8Fm8g-ibHVss3-KseLnMhzUr9xE_9f4YoZ6iUpkZZo56hIhCoDCxqmGqwL8_q4AClozhqWAjVtgeqUQipm48Ney49B5EC16pkFSvYVBxN27szUtwVqtq-xUtj8blsUQEf4AhoGm9B1A2e7DfzwLvACCwagjr8JH9x73wsd3_cdb7bgW0rDOyv7ufbLufkHqOttJw)

> These links (from workflow link) return nothing: pipelines: [1-daily-backups/dags.py](https://github.com/vesnikos/ubdc-dags/blob/doc/restructure-of-data-specs/dags/airbnb/airbnb_daily_responses/1-daily-backups/dags.py) tests: [tests.py](https://github.com/vesnikos/ubdc-dags/blob/doc/restructure-of-data-specs/dags/tests/airbnb/1-daily-backups/tests.py)

I need to re-write the that document. At the moment there's only one file that contain a pipeline. 

> 
> In the [Workflow Datasets](https://github.com/vesnikos/ubdc-dags/tree/doc/restructure-of-data-specs/dags/airbnb#workflow-datasets) I think it will be better if you link the intermediate datasets with final datasets that will be made available to researchers. 

I am purposely trying to keep the information low here. I think potentially the best way to describe relationship between dags and datasets would be to use the airflow's native [dataset ui](https://airflow.apache.org/blog/airflow-2.9.0/#dataset-ui-enhancements)

**Pull request merged**
